[package]
authors = ["Yusuke Suzuki <utatane.tea@gmail.com>"]
name = "jsc"
version = "0.1.0"

[dependencies]
url = "1.1.1"

[dependencies.jsc-sys]
path = "jsc-sys"
version = "0.1.0"

[[test]]
name = "simple"
