[package]
name = "jsc-sys"
version = "0.1.0"
authors = ["Yusuke Suzuki <utatane.tea@gmail.com>"]
links = "JavaScriptCore"
build = "build.rs"

[lib]
name = "jsc_sys"
path = "lib.rs"
crate-type = ["dylib"]

[build-dependencies]
pkg-config = "0.3"
